# Training and Testing a Model

## Load Necessary Libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error, r2_score

In [5]:
df = pd.read_csv("SPY_2000_2022.csv")
df

,Date,Close,High,Low,Open,Volume,Adj Close
0,03/01/2000,91.367500,93.134384,90.385898,93.134384,8164300,91.367500
1,04/01/2000,87.794525,90.503748,87.725813,90.170003,8089800,87.794525
2,05/01/2000,87.951553,88.913523,86.223934,87.912289,12177900,87.951553
3,06/01/2000,86.538040,88.893885,86.538040,87.715963,6227200,86.538040
4,07/01/2000,91.563873,91.563873,87.990841,88.147897,8066500,91.563873
...,...,...,...,...,...,...,...
5531,27/12/2021,450.219940,450.267096,445.267389,445.314545,56808600,450.219940
5532,28/12/2021,449.852051,451.682139,449.087945,450.653898,47274600,449.852051
5533,29/12/2021,450.427490,451.446288,448.955877,449.955819,54503000,450.427490
5534,30/12/2021,449.182221,451.861311,448.719992,450.851927,55329000,449.182221
5535,31/12/2021,448.050201,449.842547,447.776653,448.691697,65237400,448.050201

In [6]:
df.drop(columns= "Date")

           Close        High         Low        Open    Volume   Adj Close
0      91.367500   93.134384   90.385898   93.134384   8164300   91.367500
1      87.794525   90.503748   87.725813   90.170003   8089800   87.794525
2      87.951553   88.913523   86.223934   87.912289  12177900   87.951553
3      86.538040   88.893885   86.538040   87.715963   6227200   86.538040
4      91.563873   91.563873   87.990841   88.147897   8066500   91.563873
...          ...         ...         ...         ...       ...         ...
5531  450.219940  450.267096  445.267389  445.314545  56808600  450.219940
5532  449.852051  451.682139  449.087945  450.653898  47274600  449.852051
5533  450.427490  451.446288  448.955877  449.955819  54503000  450.427490
5534  449.182221  451.861311  448.719992  450.851927  55329000  449.182221
5535  448.050201  449.842547  447.776653  448.691697  65237400  448.050201

[5536 rows x 6 columns]

## spliting the data for training and testing

In [16]:
# Giving the X parameters and y parameters
X = df[["High", "Low", "Open", "Volume"]]
y = df["Adj Close"]

In [17]:
X_train, X_test, y_train, y_test  = train_test_split(X, y, 
                                                     test_size=0.2,
                                                     shuffle=False, 
                                                     random_state=35,)

## Fitting the model

In [18]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

_extracting slope and intercept_

In [19]:
slope = model.coef_
intercept = model.intercept_


print(f"Slope: {slope}")
print(f"Intercept: {intercept}")

Slope: [ 8.09337281e-01  8.00855110e-01 -6.09656651e-01  1.47180173e-11]
Intercept: -0.012968817013259581

## The estimated Regression Model is given by: $\hat{y} = \omega_0 + \omega_1 * X$
- where $\omega_0$ = bias = -0.012968817013259581  
- And $\omega_1$ = $X1$ =  8.09337281e-01  
- And $\omega_2$ = $X2$ = 8.00855110e-01  
- And $\omega_3$ = $X3$ = -6.09656651e-01   
- And $\omega_4$ = $X4$ = 1.47180173e-11

## Making Prediction

In [20]:
y_pred = model.predict(X_test)

data = {"actual": y_test, "Predicted": y_pred}

# Turning the Dictionary to a pandas dataframe
pred_df = pd.DataFrame(data)
pred_df

          actual   Predicted
4428  215.445084  215.174705
4429  212.404037  213.010764
4430  212.717697  213.094275
4431  214.826447  214.919773
4432  214.800293  214.754863
...          ...         ...
5531  450.219940  449.511504
5532  449.852051  450.461151
5533  450.427490  450.590196
5534  449.182221  450.190873
5535  448.050201  449.118679

[1108 rows x 2 columns]

## Performance of the Model on the test set

In [26]:
mse = mean_squared_error(y_pred, y_test)
rmse = np.sqrt(mse)
r2 = r2_score(y_pred, y_test)

print(f"MSE  = {mse:.4f}")
print(f"RMSE = {rmse:.4f}")
print(f"R²   = {r2:.4f}")

MSE  = 1.6843
RMSE = 1.2978
R²   = 0.9996

## Performance of the Model on the Training set

In [30]:
y_pred_train = model.predict(X_train)

mse_train = mean_squared_error(y_pred_train, y_train)
rmse_train = np.sqrt(mse_train)
r2_train = r2_score(y_pred_train, y_train)

print(f"MSE  = {mse_train:.4f}")
print(f"RMSE = {rmse_train:.4f}")
print(f"R²   = {r2_train:.4f}")

MSE  = 0.1951
RMSE = 0.4417
R²   = 0.9999

In [31]:
dta = {
    "Train" : {"MSE" : 0.1951,
               "RMSE" : 0.4417,
               "R²"  : 0.9999},
    "Test" : {"MSE"  : 1.6843,
              "RMSE" : 1.2978,
              "R²"   : 0.9996}
}

final_df = pd.DataFrame(dta)
final_df

       Train    Test
MSE   0.1951  1.6843
RMSE  0.4417  1.2978
R²    0.9999  0.9996