### Importing necessary Libraries

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [28]:
df = pd.read_excel("Multicollinearity_Dataset.xlsx")
df

,Study_Hours,Reading_Hours,Practice_Hours,Total_Study_Time,Attendance,Final_Score
0,7.12,6.27,7.51,20.79,93,47.18
1,7.93,7.32,8.64,23.70,72,49.67
2,6.04,5.27,6.28,17.65,87,45.01
3,5.59,5.01,6.33,17.03,75,44.50
4,4.72,4.14,5.46,14.25,72,39.40
...,...,...,...,...,...,...
95,9.66,8.61,10.06,28.23,96,55.73
96,3.22,2.74,3.61,9.60,76,34.86
97,4.05,3.65,4.46,12.35,92,36.46
98,8.55,8.14,8.92,25.42,79,54.33
99,9.26,8.44,10.35,27.93,88,57.95

**Checking the correlation of the dataset**

In [29]:
df.corr()

,Study_Hours,Reading_Hours,Practice_Hours,Total_Study_Time,Attendance,Final_Score
Study_Hours,1.000000,0.997068,0.996046,0.998985,0.128740,0.979627
Reading_Hours,0.997068,1.000000,0.992872,0.997795,0.125417,0.978297
Practice_Hours,0.996046,0.992872,1.000000,0.998085,0.128828,0.973630
Total_Study_Time,0.998985,0.997795,0.998085,1.000000,0.129342,0.978061
Attendance,0.128740,0.125417,0.128828,0.129342,1.000000,0.141172
Final_Score,0.979627,0.978297,0.973630,0.978061,0.141172,1.000000

### What I noticed from the correlation  
- there are positively correlated

**Assigning the X and the y parameters**

In [30]:
X = df[["Study_Hours", "Reading_Hours",
        "Practice_Hours", "Total_Study_Time", 
        "Attendance"]]

y = df["Final_Score"]

In [31]:
print(f"X has {X.ndim} dimensions")

X has 2 dimensions

### Splitting the dataset for training and testing

In [32]:
X_train, X_test, y_train, y_test =  train_test_split(X, y, 
                                                     train_size = 0.8,
                                                     shuffle = True,
                                                     random_state = 30)

**fitting the training set**

In [33]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [34]:
slope = model.coef_
intercept = model.intercept_

print(f"Slope: {slope}")
print(f"Intercept: {intercept:.4f}")

Slope: [ 5.7237943   1.92843413  0.50504087 -1.488209    0.01881841]
Intercept: 22.0598

In [35]:
y_pred = model.predict(X_test)
y_pred

array([56.30051401, 56.90947145, 37.80611482, 54.84805079, 33.58122823,
       45.69979315, 48.89667951, 56.44689904, 46.02411924, 37.27966139,
       54.92641897, 58.72254909, 49.50759312, 45.26726946, 35.97478008,
       45.52300542, 41.00291906, 44.07967941, 54.46809826, 48.11693956])

**comparing the actual value and the predicted value**

In [36]:
pred_data = {"Actual": y_test, "Predicted": y_pred}
pred_data_df = pd.DataFrame(pred_data)
pred_data_df

    Actual  Predicted
20   54.12  56.300514
91   54.37  56.909471
34   37.64  37.806115
52   53.20  54.848051
8    35.74  33.581228
74   44.53  45.699793
21   50.13  48.896680
88   57.32  56.446899
80   46.75  46.024119
89   38.17  37.279661
82   56.61  54.926419
38   59.91  58.722549
0    47.18  49.507593
77   47.72  45.267269
42   38.51  35.974780
67   47.23  45.523005
68   42.17  41.002919
92   42.94  44.079679
48   55.02  54.468098
10   46.76  48.116940

**Checking the error quotients**

In [37]:
mse = mean_squared_error(y_pred, y_test)
rmse = np.sqrt(mse)
r2 = r2_score(y_pred, y_test)

print(f"MSE  = {mse:.4f}")
print(f"RMSE = {rmse:.4}")
print(f"R²   = {r2:.4f}")

MSE  = 2.6702
RMSE = 1.634
R²   = 0.9527

**fitting the test parameters**

In [38]:
model_test = LinearRegression()
model_test.fit(X_test, y_test)

LinearRegression()

In [39]:
test_slope = model_test.coef_
test_intercept = model_test.intercept_

print(test_slope)
print(test_intercept)

[-5.23870855  1.75313215  2.84890453  1.19809413  0.02177503]
25.772443846545528

**predicting with the test parameters**

In [40]:
y_train_pred = model_test.predict(X_train)
y_train_pred

array([56.39640644, 42.49936847, 43.36415768, 44.79430723, 51.63958016,
       50.65007469, 55.14543354, 54.25618919, 37.80534043, 34.67297034,
       54.83356628, 35.88789847, 52.65665464, 37.48289369, 32.32049353,
       35.16660249, 51.00309774, 54.06580273, 39.81512627, 46.18315129,
       54.12092286, 41.18226336, 46.53108347, 45.55250626, 47.10841784,
       60.59907898, 46.24094734, 35.01503283, 54.5650964 , 38.19580366,
       52.32118613, 54.73902633, 52.83998957, 46.20841985, 48.43918635,
       54.46134668, 40.38581669, 57.39865627, 44.06991776, 43.53503548,
       40.4798106 , 58.98992714, 49.84726567, 35.54582715, 42.27427409,
       48.81713255, 35.98489863, 47.27182046, 35.91285451, 43.85681322,
       55.79309292, 35.81404707, 57.61293457, 41.01016433, 54.93896585,
       51.6485077 , 37.60042331, 57.57208844, 34.16492194, 53.79449952,
       52.58343821, 54.69449762, 55.21114768, 46.20518741, 37.14853533,
       51.56409674, 34.40280212, 40.84453599, 45.97642799, 45.3414907 ,
       46.9905863 , 48.19082919, 36.76913548, 44.30155965, 37.73464552,
       37.55346186, 40.4604856 , 37.53023296, 56.92357111, 44.72906275])

**Comparing the actual and the predicted train paramters**

In [41]:
train_df = {"Actual" : y_train,
            "Predicted" : y_train_pred}

train_pred_df = pd.DataFrame(train_df)
train_pred_df

    Actual  Predicted
93   53.93  56.396406
4    39.40  42.499368
51   42.92  43.364158
72   44.29  44.794307
1    49.67  51.639580
..     ...        ...
12   39.68  37.553462
97   36.46  40.460486
45   33.06  37.530233
99   57.95  56.923571
37   41.40  44.729063

[80 rows x 2 columns]

In [42]:
train_mse = mean_squared_error(y_train_pred, y_train)
train_rmse = np.sqrt(train_mse)
train_r2 = r2_score(y_train_pred, y_train)


print(f"MSE   = {train_mse:.4F}")
print(f"RMSE  = {train_rmse:.4F}")
print(f"R²    = {train_r2:.4F}")

MSE   = 6.7961
RMSE  = 2.6069
R²    = 0.8816

In [43]:
train_error = {
    "Train" : {
        "MSE" :  2.6702,
        "RMSE" : 1.634,
        "R²" : 0.9527
    },
    "Test" : {
        "MSE" : 6.7961,
        "RMSE" : 2.6069,
        "R²" : 0.8816
    }
}

train_error_df = pd.DataFrame(train_error)
train_error_df

       Train    Test
MSE   2.6702  6.7961
RMSE  1.6340  2.6069
R²    0.9527  0.8816

## Using a Lasso() to solve the problem

### importing the required Libraries

In [44]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet
from sklearn.model_selection import GridSearchCV

defining the different models

In [45]:
model1 = Lasso()
model2 = Ridge()
model3 = ElasticNet()

**Hyperparameter tuning for the lasso Regression**

In [46]:
# Hyperparameter grid
param_grid_lasso = {
    "alpha": [0.001, 0.01, 0.1, 1, 10, 100]
}

In [47]:
# Grid Search with 5-fold Cross Validation
grid_lasso  = GridSearchCV(
    estimator = model1,
    param_grid = param_grid_lasso,
    cv = 5,
    scoring = "neg_mean_squared_error"
)

grid_lasso.fit(X_train, y_train)

print("Best alpha:", grid_lasso.best_params_)
print("Best CV Score: ", grid_lasso.best_score_)

best_lasso = grid_lasso.best_estimator_

c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.571636e+01, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.237777e+01, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.217629e+01, tolerance: 5.380e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.682151e+01, tolerance: 4.456e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.245907e+01, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.719033e+00, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.173507e+00, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.463478e+00, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(

Best alpha: {'alpha': 0.01}
Best CV Score:  -3.6893341554027117

## Hyperparameter Tuning for Elastic Net

In [48]:
param_grid_elastic = {
    "alpha": [0.001, 0.01, 0.1, 1, 10],
    "l1_ratio": [0.2, 0.4, 0.6, 0.8, 1.0]
}

grid_elastic = GridSearchCV(
    estimator= model3,
    param_grid = param_grid_elastic,
    cv= 5,
    scoring= "neg_mean_squared_error"
)

grid_elastic.fit(X_train, y_train)
print("Best Parameters: ", grid_elastic.best_params_)
print("Best CV Score:", grid_elastic.best_score_)

best_elastic = grid_elastic.best_estimator_

c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.931064e+01, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.514976e+01, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.970687e+01, tolerance: 5.380e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.729861e+01, tolerance: 4.456e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.861603e+01, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.566701e+01, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.184138e+01, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.226703e+01, tolerance: 5.380e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.929321e+01, tolerance: 4.456e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.158853e+01, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.218754e+01, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.861091e+01, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.518854e+01, tolerance: 5.380e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.151615e+01, tolerance: 4.456e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.488019e+01, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.887135e+01, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.545693e+01, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.848806e+01, tolerance: 5.380e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.400730e+01, tolerance: 4.456e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.850164e+01, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.571636e+01, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.237777e+01, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.217629e+01, tolerance: 5.380e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.682151e+01, tolerance: 4.456e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.245907e+01, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.961062e+00, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.995440e+01, tolerance: 5.380e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.647608e+01, tolerance: 4.456e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.909574e+01, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.376402e+01, tolerance: 5.380e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.717135e+00, tolerance: 4.456e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.019681e+01, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.090063e+00, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.372452e+00, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.003298e+00, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.916854e+00, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.719033e+00, tolerance: 4.565e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.173507e+00, tolerance: 5.231e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.463478e+00, tolerance: 5.063e-01
  model = cd_fast.enet_coordinate_descent(

Best Parameters:  {'alpha': 0.01, 'l1_ratio': 0.2}
Best CV Score: -3.6719266555435226

c:\Users\McImaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.277104e+01, tolerance: 6.206e-01
  model = cd_fast.enet_coordinate_descent(

## **Hyperparameter tuning for Ridge**

In [49]:
param_grid_ridge = {
    "alpha": [0.001, 0.01, 0.1, 1, 10]
}

grid_ridge = GridSearchCV(
    estimator = model2,
    cv = 5,
    param_grid = param_grid_ridge,
    scoring = "neg_mean_squared_error"
)

grid_ridge.fit(X_train, y_train)
print("Best Parameter:", grid_ridge.best_params_)
print("Best CV score:", grid_ridge.best_score_)

best_ridge = grid_ridge.best_estimator_

Best Parameter: {'alpha': 1}
Best CV score: -3.6660161999820318

## Making predictions

In [52]:
lasso_pred = best_lasso.predict(X_test)

ridge_pred = best_ridge.predict(X_test)

elastic_pred = best_elastic.predict(X_test)

**Evaluationg the models**

In [53]:
models  = {
    "Lasso": (best_lasso, lasso_pred),
    "Ridge": (best_ridge, ridge_pred),
    "Elastic Net" : (best_elastic, elastic_pred)
}

for name, (model, pred) in models.items():
    mse = mean_squared_error(y_test, pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, pred)
    
    print(f"\n{name}")
    print(f"Best Parameters : {model.get_params()}")
    print(f"MSE        :{mse:.4f}")
    print(f"RMSE       :{rmse:.4f}")
    print(f"R²         :{r2:.4f}")

Lasso
Best Parameters : {'alpha': 0.01, 'copy_X': True, 'fit_intercept': True, 'max_iter': 1000, 'positive': False, 'precompute': False, 'random_state': None, 'selection': 'cyclic', 'tol': 0.0001, 'warm_start': False}
MSE        :2.5739
RMSE       :1.6043
R²         :0.9475

Ridge
Best Parameters : {'alpha': 1, 'copy_X': True, 'fit_intercept': True, 'max_iter': None, 'positive': False, 'random_state': None, 'solver': 'auto', 'tol': 0.0001}
MSE        :2.4566
RMSE       :1.5673
R²         :0.9499

Elastic Net
Best Parameters : {'alpha': 0.01, 'copy_X': True, 'fit_intercept': True, 'l1_ratio': 0.2, 'max_iter': 1000, 'positive': False, 'precompute': False, 'random_state': None, 'selection': 'cyclic', 'tol': 0.0001, 'warm_start': False}
MSE        :2.4752
RMSE       :1.5733
R²         :0.9496